/* Style reminder: Editorial Growth Ledger — exactly two static home screens, no carousel and no long scrolling homepage. Screen one communicates; screen two routes visitors to the dedicated detail pages. */
import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, Layers3, Sparkles, Users } from "lucide-react";
import { Link } from "wouter";

const STORAGE = "/manus-storage/";
const AGENCY_LOGO = `${STORAGE}ecommerce-hub-agency-logo_5b64a04c.jpeg`;

const destinations = [
  { number: "01", label: "Past Work", title: "Proof with a pulse.", copy: "Open the client archive and inspect the first three live project chapters.", href: "/work", icon: BriefcaseBusiness, tone: "coral" },
  { number: "02", label: "Services", title: "Clear services. Useful movement.", copy: "See every capability e_commerce.hub brings to businesses and startups.", href: "/services", icon: Sparkles, tone: "blue" },
  { number: "03", label: "Packages", title: "Choose your starting point.", copy: "Compare Basic, High Level, Advance, and Premium scopes.", href: "/packages", icon: Layers3, tone: "navy" },
  { number: "04", label: "Team", title: "Meet the people behind it.", copy: "See Abhishek, Yash, and Himanshu building the next move together.", href: "/team", icon: Users, tone: "coral" },
];

export default function CompactHome() {
  return <div className="compact-home"><header className="compact-header"><a className="compact-lockup" href="#top" aria-label="e_commerce.hub home"><img src={AGENCY_LOGO} alt="" /><span><strong>e_commerce<span>.hub</span></strong><small>LOCAL TO GLOBAL</small></span></a><nav className="compact-header-links" aria-label="Primary navigation"><a href="/work">Past Work</a><a href="/services">Services</a><a href="/packages">Packages</a><a href="/team">Team</a><a href="/studio#contact">Contact</a><a className="compact-explore-link" href="#explore">Explore screen 02 <ArrowDownRight size={15} /></a></nav></header><main id="top"><section className="compact-screen compact-screen-hero"><div className="compact-hero-copy"><p className="eyebrow"><span>e_commerce.hub / 01</span> Growth partners for the next move</p><h1>Make your next<br /><em>market feel closer.</em></h1><p>Marketing, social growth, and websites for businesses and startups ready to move from local attention to wider demand.</p><div className="compact-hero-actions"><a className="button button-coral" href="#explore">Explore the studio <ArrowDownRight size={16} /></a><a className="compact-contact-link" href="mailto:ecommercehub54@gmail.com">ecommercehub54@gmail.com <ArrowUpRight size={15} /></a></div><div className="compact-proof-line"><span>01 / Strategy</span><span>02 / Social</span><span>03 / Web</span></div></div><div className="compact-hero-art"><div className="compact-art-label">local → global</div><img src={`${STORAGE}ecommerce-hub-hero_598609b3.jpg`} alt="Abstract coral and cobalt collage representing a business moving forward" /><span className="compact-art-stamp">Built for<br />momentum</span></div></section><section id="explore" className="compact-screen compact-screen-explore"><div className="compact-explore-heading"><p className="eyebrow"><span>e_commerce.hub / 02</span> Explore the studio</p><h2>Choose the<br /><em>next page.</em></h2><p>Two static screens. Four clear destinations. Open the detail you came for without wading through a long homepage.</p></div><div className="compact-destination-grid">{destinations.map((destination) => { const Icon = destination.icon; return <Link key={destination.number} className={`compact-destination compact-destination-${destination.tone}`} href={destination.href}><div className="compact-destination-top"><span>{destination.number} / {destination.label}</span><Icon size={18} /></div><h3>{destination.title}</h3><p>{destination.copy}</p><span className="compact-destination-open">Open page <ArrowUpRight size={15} /></span></Link>; })}</div></section></main><footer className="compact-footer"><span>© 2026 e_commerce.hub</span><span>Marketing / Social / Web</span><a href="/studio#contact">Start a conversation <ArrowUpRight size={15} /></a></footer></div>;
}
