/* Style reminder: Editorial Growth Ledger — keep warm paper, ink navy, coral action moments, cobalt structure, chartreuse flashes, ruled metadata, and crisp motion. Dedicated detail pages should feel like focused studio briefs, not utility dashboards. */
import { ArrowDownRight, ArrowUpRight, Check, CircleArrowOutUpRight, Mail, MessageCircle } from "lucide-react";
import { Link } from "wouter";

const projects = [
  { number: "01", title: "Pachorekar Jewellers", type: "Jewellery catalogue + customer journey", detail: "A catalogue-led jewellery experience with product categories, appointment booking, care guidance, location, FAQ, and direct contact paths.", link: "https://www.pachorekarjewellers.co.in/", tone: "coral" },
  { number: "02", title: "Angad International", type: "Agriculture export website", detail: "A focused export experience for fresh produce, spices, and dehydrated products, supported by product discovery, export capabilities, and inquiry CTAs.", link: "https://www.angadinternational.com/", tone: "blue" },
  { number: "03", title: "Sahyadri Global Traders", type: "Global agriculture trade platform", detail: "A global agriculture-trade experience centered on export products, quality assurance, cold-chain logistics, insight articles, and direct enquiries.", link: "https://www.sahyadriglobaltraders.com/", tone: "navy" },
];

const services = [
  { number: "01", title: "Marketing direction", copy: "Positioning, content direction, launch thinking, and practical campaign priorities that make the next move clearer." },
  { number: "02", title: "Social media growth", copy: "A useful content system for showing up consistently, sounding like a real business, and earning the next click." },
  { number: "03", title: "Website design + build", copy: "Clear, confident websites for businesses and startups that need to turn interest into an honest conversation." },
  { number: "04", title: "Brand communication", copy: "A sharper point of view across words, visuals, and touchpoints so your business feels consistent wherever people meet it." },
];

const packages = [
  { number: "01", name: "Basic", note: "A focused starting point", copy: "For businesses that need a clear first step and a reliable digital foundation.", includes: ["Discovery and direction session", "Essential marketing guidance", "Social profile improvement plan", "Clear next-step roadmap"], tone: "paper" },
  { number: "02", name: "High Level", note: "A sharper market presence", copy: "For teams ready to bring strategy, content, and customer touchpoints into one stronger system.", includes: ["Positioning and content direction", "Social media growth plan", "Website structure recommendations", "Campaign-ready content priorities"], tone: "blue" },
  { number: "03", name: "Advance", note: "Built for consistent movement", copy: "For growing businesses that want an active partner across marketing, social, and web execution.", includes: ["Integrated marketing direction", "Ongoing social growth support", "Conversion-focused website guidance", "Monthly movement review"], tone: "coral" },
  { number: "04", name: "Premium", note: "A complete growth partner", copy: "For ambitious brands that want close collaboration across the full journey from local attention to wider demand.", includes: ["Full-funnel growth direction", "Priority creative and social support", "Website strategy and build oversight", "Dedicated partnership planning"], tone: "navy" },
];

function DetailShell({ eyebrow, title, intro, children }: { eyebrow: string; title: React.ReactNode; intro: string; children: React.ReactNode }) {
  return <div className="detail-page"><header className="detail-page-nav"><Link href="/" className="detail-back">e_commerce<span>.hub</span></Link><Link href="/" className="detail-home-link"><ArrowDownRight size={16} /> Back to home</Link></header><main><section className="detail-page-hero"><div><p className="eyebrow"><span>e_commerce.hub / brief</span> {eyebrow}</p><h1>{title}</h1><p>{intro}</p><div className="detail-page-actions"><a href="/studio#contact" className="button button-coral">Start a conversation <ArrowUpRight size={16} /></a><Link href="/" className="text-link detail-light-link">Return to homepage <ArrowDownRight size={16} /></Link></div></div><div className="detail-page-index" aria-hidden="true">/ / /<strong>01</strong><span>focused studio brief</span></div></section>{children}</main><footer className="detail-page-footer"><div><strong>e_commerce<span>.hub</span></strong><p>Marketing, social growth, and websites for the next move.</p></div><div><a href="mailto:ecommercehub54@gmail.com"><Mail size={15} /> ecommercehub54@gmail.com</a><a href="https://wa.me/918378976036" target="_blank" rel="noreferrer"><MessageCircle size={15} /> WhatsApp the studio</a></div></footer></div>;
}

export function PastWorkPage() {
  return <DetailShell eyebrow="Past work" title={<>Proof with a<br /><em>pulse.</em></>} intro="Explore the first three client chapters in the e_commerce.hub work archive. Each link opens the live public project so you can inspect the work directly."><section className="detail-content-section"><div className="detail-section-heading"><p className="eyebrow"><span>Archive / 01—03</span> Selected client work</p><h2>Work that makes<br /><em>the next step visible.</em></h2></div><div className="detail-project-list">{projects.map((project) => <article className={`detail-project-row detail-tone-${project.tone}`} key={project.number}><div className="detail-project-art"><span>{project.number}</span><div className="detail-art-line" /><div className="detail-art-circle" /></div><div><p>{project.type}</p><h3>{project.title}</h3><span>{project.detail}</span><a className="button button-navy" href={project.link} target="_blank" rel="noreferrer">Visit live project <CircleArrowOutUpRight size={15} /></a></div></article>)}</div></section><section className="detail-next-band"><span>Next chapter</span><h2>Have a project<br /><em>worth moving?</em></h2><a href="/studio#contact" className="button button-coral">Tell us what you’re building <ArrowUpRight size={16} /></a></section></DetailShell>;
}

export function ServicesPage() {
  return <DetailShell eyebrow="Services" title={<>Clear services.<br /><em>Useful movement.</em></>} intro="Pick the capability you need now, or combine a few into a practical route from local attention to wider digital demand."><section className="detail-content-section"><div className="detail-section-heading"><p className="eyebrow"><span>Services / 01—04</span> What we move</p><h2>Choose the work<br /><em>that unlocks yours.</em></h2></div><div className="detail-service-list">{services.map((service) => <article key={service.number}><span>{service.number}</span><div><h3>{service.title}</h3><p>{service.copy}</p></div><ArrowUpRight size={20} /></article>)}</div></section><section className="detail-process"><p className="eyebrow eyebrow-light"><span>How it works</span> A clear route</p><h2>Brief → direction<br /><em>→ useful build.</em></h2><div className="detail-process-grid"><span><b>01</b> Find the signal</span><span><b>02</b> Build the system</span><span><b>03</b> Move the number</span></div></section></DetailShell>;
}

export function PackagesPage() {
  return <DetailShell eyebrow="Packages" title={<>Choose the right<br /><em>starting point.</em></>} intro="Four ways to work together. Every package can be shaped around your goals, and final pricing will be declared soon."><section className="detail-content-section"><div className="detail-section-heading"><p className="eyebrow"><span>Packages / 01—04</span> Ways to work together</p><h2>A package for the<br /><em>next move.</em></h2></div><div className="detail-package-grid">{packages.map((pack) => <article className={`detail-package-card package-${pack.tone}`} key={pack.number}><div className="package-topline"><span>{pack.number}</span><span>Price declared soon</span></div><p className="package-note">{pack.note}</p><h3>{pack.name}</h3><p>{pack.copy}</p><ul>{pack.includes.map((item) => <li key={item}><Check size={14} /> {item}</li>)}</ul><a href="/studio#contact" className="package-cta">Ask about {pack.name} <ArrowUpRight size={15} /></a></article>)}</div></section><section className="detail-price-note"><span>Pricing note / 2026</span><h2>Tell us what you need<br /><em>before we price the path.</em></h2><p>Send a short brief and we’ll help match the scope to the right package. Final pricing will be shared directly.</p><a href="/studio#contact" className="button button-coral">Request a package conversation <ArrowUpRight size={16} /></a></section></DetailShell>;
}
