/* Style reminder: Editorial Growth Ledger — warm paper, ink navy, coral action color, clean directory navigation, and honest team information only. */
import { ArrowDownRight, ArrowUpRight, Instagram, Mail, Phone } from "lucide-react";
import { Link } from "wouter";

const STORAGE = "/manus-storage/";
const members = [
  { number: "01", name: "Abhishek Damale", role: "Co-founder + Developer", education: "3rd Year Engineering Student · Computer Science · Savitribai Phule Pune University", focus: "Strategy, positioning, web development, and the question that makes the whole thing click.", email: "abhishekdamale67@gmail.com", phone: "9112658707", instagram: "https://www.instagram.com/abhishek_damale006?igsi=YTF1NTM3bHJ1ZDdr", photo: `${STORAGE}abhishek-damale-portrait_abc61bb6.png`, tone: "coral" },
  { number: "02", name: "Yash Mete", role: "Co-founder + Developer", education: "3rd Year Engineering Student · Computer Science · Savitribai Phule Pune University", focus: "Digital systems, social momentum, and the details people remember.", email: "yashmete266@gmail.com", phone: "8378976036", instagram: "https://www.instagram.com/yash_mete_patil?igsi=OGRpbXZ5OWtvcWJh", photo: `${STORAGE}yash-mete-portrait_cf15b695.jpeg`, tone: "blue" },
];

const destinations = [
  { label: "Past Work", copy: "Inspect the first three live project chapters.", href: "/work" },
  { label: "Services", copy: "See the capabilities we bring to clients.", href: "/services" },
  { label: "Packages", copy: "Compare four ways to begin together.", href: "/packages" },
];

export default function TeamPage() {
  return <div className="team-page"><header className="detail-page-nav"><Link className="detail-back" href="/">e_commerce<span>.hub</span></Link><Link className="detail-home-link" href="/explore"><ArrowDownRight size={16} /> Explore studio</Link></header><main><section className="team-page-hero"><div><p className="eyebrow eyebrow-light"><span>e_commerce.hub / 04</span> The people behind it</p><h1>Two minds.<br /><em>One useful move.</em></h1><p>A small team of developers and strategists building clearer digital paths for businesses and startups.</p></div><div className="team-page-index"><span>Team / 01—02</span><strong>02</strong><small>close collaboration / clear delivery</small></div></section><section className="team-page-directory"><div className="team-page-heading"><p className="eyebrow"><span>Meet the team</span> Built close</p><h2>People with<br /><em>somewhere to go.</em></h2></div><div className="team-page-grid">{members.map((member) => <article className={`team-page-card team-page-card-${member.tone}`} key={member.name}><div className="team-page-card-top"><span>{member.number} / Team member</span><ArrowUpRight size={18} /></div><div className="team-page-photo"><img loading="lazy" src={member.photo} alt={member.name} /><span>{member.number} / 02</span></div><div className="team-page-card-copy"><p>{member.role}</p><h3>{member.name}</h3><span>{member.focus}</span><small>{member.education}</small><div className="team-page-actions">{member.email && <a href={`mailto:${member.email}`} aria-label={`Email ${member.name}`}><Mail size={14} /> Email</a>}<a href={`tel:+91${member.phone}`} aria-label={`Call ${member.name}`}><Phone size={14} /> Call</a><a href={member.instagram} target="_blank" rel="noreferrer" aria-label={`Open ${member.name} Instagram`}><Instagram size={14} /> Instagram</a></div></div></article>)}</div></section><section className="team-page-links"><p className="eyebrow"><span>Continue exploring</span> The next useful page</p><div className="team-page-link-grid">{destinations.map((destination) => <Link href={destination.href} className="team-page-link-card" key={destination.label}><div><strong>{destination.label}</strong><ArrowUpRight size={16} /></div><p>{destination.copy}</p></Link>)}</div></section></main><footer className="detail-page-footer"><div><strong>e_commerce<span>.hub</span></strong><p>Marketing, social growth, and websites for the next move.</p></div><a href="/studio#contact">Start a conversation <ArrowUpRight size={16} /></a></footer></div>;
}
